#!/usr/bin/env bash

# back to previous directory
cd ../


# check updates
sudo apt update
sudo apt-get update


# remove python2.7.x and install python3 and pip3
sudo apt purge -y python2.7-minimal
sudo apt-get install python3-pip


# install jetson-stats
sudo -H pip install -U jetson-stats


# install jetson-fan-ctl
git clone https://github.com/Pyrestone/jetson-fan-ctl.git
cd ./jetson-fan-ctl
sudo ./install.sh


# install torch and torchvision
# install torch v1.9.0 
wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.9.0-cp36-cp36m-linux_aarch64.whl
sudo apt-get update
sudo apt-get install libopenblas-base libopenmpi-dev 
pip install Cython
pip install torch-1.9.0-cp36-cp36m-linux_aarch64.whl

# install torchvision v0.10.0
sudo apt-get update
sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
pip install torchvision


# install tensorflow
sudo apt-get update
sudo apt-get install libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran
sudo pip3 install -U pip testresources setuptools==49.6.0
sudo pip3 install -U numpy==1.19.4 future==0.18.2 mock==3.0.5 h5py==2.10.0 keras_preprocessing==1.1.1 keras_applications==1.0.8 gast==0.2.2 futures protobuf pybind11
sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v45 tensorflow